steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --location=us-central1-c
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod


